using Intersect.Framework.Core.MiniGames.Blackjack;
using Intersect.Server.MiniGames.Blackjack;

var passed = 0; var failed = 0;
var now = new DateTimeOffset(2026, 1, 1, 0, 0, 0, TimeSpan.Zero);
void Test(string name, Action test) { try { test(); ++passed; Console.WriteLine("PASS blackjack: " + name); } catch(Exception e) { ++failed; Console.Error.WriteLine("FAIL blackjack: " + name + "\n" + e); } }
void Check(bool c, string m) { if(!c) throw new InvalidOperationException(m); }
int C(string text) => "23456789TJQKA".IndexOf(text[0]) + "CDHS".IndexOf(text[1]) * 13;
int[] Deck(params string[] prefix) { var d = Enumerable.Range(0, 312).Select(i=>i%52).ToList(); var p=prefix.Select(C).ToArray(); foreach(var c in p) { if(!d.Remove(c)) throw new Exception("Fixture card exhausted"); } return p.Concat(d).ToArray(); }
(BlackjackTable T, Guid P) Table(string[] prefix, bool h17=false, long chips=100, long bank=10000) { var t = new BlackjackTable(new BlackjackRules(5,100,2,100,5,h17),bank,()=>Deck(prefix)); var p=Guid.NewGuid(); Check(t.Join(p,"Alice",chips)==BlackjackError.None,"join"); Check(t.Begin(t.Revision,now)==BlackjackError.None,"begin"); return (t,p); }
void Bet(BlackjackTable t, Guid p,long n=10) => Check(t.Bet(p,t.HandId,t.Revision,n,now)==BlackjackError.None,"bet");
void Act(BlackjackTable t,Guid p,BlackjackAction a) => Check(t.Act(p,t.HandId,t.Revision,a,now)==BlackjackError.None,"act "+a);
void Finish(BlackjackTable t,Guid p) { var clock=now;for(var i=0;i<200 && t.Stage!=BlackjackStage.Finished;i++){clock=clock.AddSeconds(6);t.Tick(clock);} Check(t.Stage==BlackjackStage.Finished,"finish");Check(t.Snapshot(p).Seats.Sum(s=>s.Chips)+t.Bank==10100,"conservation"); }
Test("Aces are soft only while valued eleven",()=>{ Check(BlackjackValues.Count(new[]{C("AC"),C("AH"),C("9S")})==(21,true),"soft");Check(BlackjackValues.Count(new[]{C("AC"),C("AH"),C("9S"),C("KD")})==(21,false),"hard"); });
Test("Natural pays exact 3:2 and only once",()=>{var(t,p)=Table(new[]{"AC","9D","KH","8S"});Bet(t,p);Finish(t,p);Check(t.Snapshot(p).Seats[0].Chips==115,"natural payout");t.Tick(now.AddHours(1));Check(t.Snapshot(p).Seats[0].Chips==115,"duplicate");});
Test("Both naturals push",()=>{var(t,p)=Table(new[]{"AC","AD","KH","KS"});Bet(t,p);Finish(t,p);Check(t.Snapshot(p).Seats[0].Chips==100,"push");});
Test("Dealer peek settles before doubles",()=>{var(t,p)=Table(new[]{"5C","AD","6H","KS"});Bet(t,p);Check(t.Stage==BlackjackStage.Finished,"peek");Check(t.Act(p,t.HandId,t.Revision,BlackjackAction.Double,now)==BlackjackError.NotYourTurn,"post natural double");Check(t.Snapshot(p).Seats[0].Chips==90,"loss");});
Test("Hidden dealer hole also hides total",()=>{var(t,p)=Table(new[]{"5C","9D","6H","AS"});Bet(t,p);var s=t.Snapshot(p);Check(s.DealerHoleHidden && s.DealerCards.SequenceEqual(new[]{C("9D")}) && s.DealerTotal==9 && !s.DealerSoft,"hole leak");});
Test("Double takes one card and pays doubled stake",()=>{var(t,p)=Table(new[]{"5C","9D","6H","8S","KC"});Bet(t,p);Act(t,p,BlackjackAction.Double);Finish(t,p);Check(t.Snapshot(p).Seats[0].Chips==120,"double");});
Test("Split plays two hands and allows double after split",()=>{var(t,p)=Table(new[]{"8C","9D","8H","8S","3C","2C","KC","QD"});Bet(t,p);Act(t,p,BlackjackAction.Split);Act(t,p,BlackjackAction.Double);Act(t,p,BlackjackAction.Double);Finish(t,p);Check(t.Snapshot(p).Seats[0].Hands.Length==2 && t.Snapshot(p).Seats[0].Chips==140,"split-double");});
Test("Split aces get one card, twenty-one is not a natural",()=>{var(t,p)=Table(new[]{"AC","9D","AH","8S","KC","QD"});Bet(t,p);Act(t,p,BlackjackAction.Split);Finish(t,p);Check(t.Snapshot(p).Seats[0].Chips==120 && t.Snapshot(p).Seats[0].Hands.All(h=>!h.Natural && h.Cards.Length==2),"aces");});
Test("No split of merely equal-valued face ranks",()=>{var(t,p)=Table(new[]{"QC","9D","KH","8S"});Bet(t,p);Check(!t.Snapshot(p).CanSplit,"different ranks");});
Test("No double after hit",()=>{var(t,p)=Table(new[]{"2C","9D","3H","8S","2D"});Bet(t,p);Act(t,p,BlackjackAction.Hit);Check(!t.Snapshot(p).CanDouble,"double after hit");});
Test("Soft seventeen dealer stands by default",()=>{var(t,p)=Table(new[]{"TC","AD","8H","6S","4C"});Bet(t,p);Act(t,p,BlackjackAction.Stand);Finish(t,p);Check(t.Snapshot(p).DealerCards.Length==2 && t.Snapshot(p).Seats[0].Chips==110,"s17");});
Test("Configured soft seventeen dealer hits",()=>{var(t,p)=Table(new[]{"TC","AD","8H","6S","4C"},true);Bet(t,p);Act(t,p,BlackjackAction.Stand);Finish(t,p);Check(t.Snapshot(p).DealerTotal==21 && t.Snapshot(p).Seats[0].Chips==90,"h17");});
Test("Bust loses even when dealer could bust",()=>{var(t,p)=Table(new[]{"TC","9D","8H","6S","KC"});Bet(t,p);Act(t,p,BlackjackAction.Hit);Finish(t,p);Check(t.Snapshot(p).Seats[0].Chips==90,"bust");});
Test("Bet validation and revision replay",()=>{var(t,p)=Table(new[]{"5C","9D","6H","8S"});var r=t.Revision;Check(t.Bet(p,t.HandId,r,3,now)==BlackjackError.InvalidBet,"odd");Check(t.Bet(p,t.HandId,r,0,now)==BlackjackError.InvalidBet,"zero");Bet(t,p);var s=t.Snapshot(p);Check(t.Bet(p,t.HandId,r,10,now)==BlackjackError.StaleState && t.Snapshot(p).Seats[0].Chips==s.Seats[0].Chips,"replay");});
Test("Bank exposure refuses an unfunded promise",()=>{var(t,p)=Table(new[]{"5C","9D","6H","8S"},bank:40);Check(t.Bet(p,t.HandId,t.Revision,12,now)==BlackjackError.BankTooLow,"bank");Check(t.Snapshot(p).Seats[0].Chips==100,"debit on reject");});
Test("Timeout stands without inventing a wager",()=>{var(t,p)=Table(new[]{"TC","9D","8H","8S"});Bet(t,p);Finish(t,p);Check(t.Snapshot(p).Seats[0].Chips==110,"timeout");});
Test("Leaving during play does not refund a losing hand",()=>{var(t,p)=Table(new[]{"TC","9D","6H","8S"});Bet(t,p);t.Leave(p,now);Finish(t,p);Check(t.Snapshot(p).Seats[0].Chips==90,"leave erased loss");});
Test("Leaving during betting cancels only the unstarted wager",()=>{var(t,p)=Table(new[]{"5C","9D","6H","8S"});var q=Guid.NewGuid();Check(t.Join(q,"Nora",100,true)==BlackjackError.None,"npc");t.Tick(now.AddSeconds(6));Check(t.Stage==BlackjackStage.Waiting,"no human bet round not cancelled");Check(t.Snapshot(p).Seats.Sum(s=>s.Chips)==200,"unstarted lost chips");});
Test("Two players independently face one dealer",()=>{var t=new BlackjackTable(new BlackjackRules(2,100,2,100,5),10000,()=>Deck("TC","9H","9D","8C","7H","8S"));var a=Guid.NewGuid();var b=Guid.NewGuid();t.Join(a,"Alice",100);t.Join(b,"Bob",100);t.Begin(t.Revision,now);Bet(t,a);Bet(t,b);Check(t.Snapshot(a).ActingSeat==0,"turn order");Check(t.Act(b,t.HandId,t.Revision,BlackjackAction.Hit,now)==BlackjackError.NotYourTurn,"out of turn");Act(t,a,BlackjackAction.Stand);Act(t,b,BlackjackAction.Stand);for(var i=1;i<10;i++)t.Tick(now.AddSeconds(i));var s=t.Snapshot(a);Check(s.Seats[0].Chips==110 && s.Seats[1].Chips==90 && t.Bank==10000,"independent settlement");});
Test("Snapshots are detached and never mutate authority",()=>{var(t,p)=Table(new[]{"5C","9D","6H","8S"});Bet(t,p);var s=t.Snapshot(p);s.DealerCards[0]=51;s.Seats[0].Hands[0].Cards[0]=51;Check(t.Snapshot(p).DealerCards[0]==C("9D") && t.Snapshot(p).Seats[0].Hands[0].Cards[0]==C("5C"),"alias");});
Test("Random shoes conserve balances for complete rounds",()=>{for(var game=0;game<200;game++){var t=new BlackjackTable(new BlackjackRules(5,100,2,100,5),100000);var ids=Enumerable.Range(0,5).Select(_=>Guid.NewGuid()).ToArray();foreach(var p in ids)t.Join(p,"Player",100);t.Begin(t.Revision,now);foreach(var p in ids)Bet(t,p);for(var i=1;i<=100 && t.Stage!=BlackjackStage.Finished;i++){var s=t.Snapshot(ids[0]);if(s.Stage==BlackjackStage.Players){var p=s.Seats.Single(x=>x.Seat==s.ActingSeat).PlayerId;var v=t.Snapshot(p);var total=v.Seats.Single(x=>x.PlayerId==p).Hands[v.ActingHand].Total;Act(t,p,total<17?BlackjackAction.Hit:BlackjackAction.Stand);}else t.Tick(now.AddSeconds(i*6));}Check(t.Stage==BlackjackStage.Finished && t.Snapshot(ids[0]).Seats.Sum(s=>s.Chips)+t.Bank==100500,"random conservation");}});
Console.WriteLine($"{passed}/{passed+failed} blackjack engine groups passed.");Environment.ExitCode=failed==0?0:1;
